name: Build

on:
  push:
    branches:
      - master

jobs:
    test:
      name: Build
      runs-on: macos-latest
      strategy:
          matrix:
            destination: ['platform=iOS Simulator,name=iPhone 11']

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run:
             xcodebuild clean build -resultBundlePath xccov.xcresult -project CleanCodeTest.xcodeproj -scheme CleanCodeTest -destination "${destination}" -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          env:
           destination: ${{ matrix.destination }}
        - name: Publish Code Coverage To Code Climate
          run:  |
            xcrun xccov view --report --json xccov.xcresult > coverage.json
            rm 'xccov.xcresult'
             export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64  > ./cc-test-reporter
             chmod +x ./cc-test-reporter
             ./cc-test-reporter before-build
             ./cc-test-reporter format-coverage -t xccov
             ./cc-test-reporter upload-coverage -d
          env:
           CC_TEST_REPORTER_ID: 1b30203e616a0d1e4ef03487f96008740987235a471a7784ffffeeb71bcd1b8c
           

