name: Build

on: 
  push:
    branches:
      - master

jobs:
    test:
      name: Build
      runs-on: macos-latest
      strategy:
          matrix:
            destination: ['platform=iOS Simulator,name=iPhone 11']

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run: 
             xcodebuild clean build -project CleanCodeTest.xcodeproj -scheme CleanCodeTest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          env:
           destination: ${{ matrix.destination }}
        - name: Publish Code Coverage To Code Climate
        run: |
          ./gradlew jacocoFix
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64  > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter format-coverage -t jacoco
          ./cc-test-reporter upload-coverage -d
        env:
          CC_TEST_REPORTER_ID: 0762e2e0f516de5ebe1df0f0c628dcf26ea02008e766aed8ba7d1001aa442410

           

    

#<<<<<<< HEAD
##on:push:
##    branches:
##      - master
##name: Build
##jobs:
##  test:
##    name: Build
##    runs-on: macOS-latest
##    strategy:
##        matrix:
##          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11', 'platform=tvOS Simulator,OS=13.2,name=Apple TV 4K']
##    steps:
##      - name: Checkout
##        uses: actions/checkout@master
##      - name: Build
##        run: |
##          cd CleanCodeTest
##          xcodebuild clean build -project CleanCodeTest.xcodeproj -scheme CleanCodeTest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
##        env:
##         destination: ${{ matrix.destination }}
#=======
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v
#>>>>>>> 83bc638be5fac9e8f27be83b41bb0511ef0eca07
